version: "3.9"
services:
  blog-post:
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - '4000:4000'

  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    user: root
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
